config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :locations do
    resources :comments
  end
  get 'homepage/index'
  resources :places
  root 'homepage#index'
  resources :reports
  get 'police/index'
  get 'news/index'
  resources :contacts, only: [:new, :create]
  get 'search', to: "places#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
# class Admin < ApplicationRecord
#   # Include default devise modules. Others available are:
#   # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
#   devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :location
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,   :validate => true
	attribute :message,   :validate => true
	attribute :email,   :validate => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
	def headers 
		{
			:subject => "Contact Form",
			:to => "crimeguardapp@gmail.com",
			:from => %("#{name}" <#{email}>)
		}
	end
end
	

app/models/location.rb
class Location < ApplicationRecord
	serialize :image, JSON
	has_many :comments, dependent: :destroy
	has_one_attached :image
	
	validates :datetime, presence: true
	validates :address, presence: true
	
	geocoded_by :address
	after_validation :geocode, if: :address_changed?

	def self.search(search)
		if search
			location = Location.find_by(city: search)
			if location
				self.where(id: location)
			else
				Location.all
			end
		else
			Location.all
		end
	end
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @location = Location.find(params[:location_id])
        @comment = @location.comments.create(comment_params)
        redirect_to location_path(@location)
    end

    private def comment_params
        params.require(:comment).permit(:username, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[ show edit update destroy ]
  before_action :authenticate_model!, only: %i[ edit new ]

  # GET /locations or /locations.json
  def index
    @locations = Location.where(['city LIKE ?', "%#{params[:search]}%"])
  end

  # GET /locations/1 or /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations or /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: "Report Form was successfully created." }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: "Report Form was successfully updated." }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: "Report Form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:address, :city, :typec, :description, :image, :datetime, :latitude, :longitude, :search)
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    news= News.new("7f3dca4f47724527b0737614b76299a2")
    @news = news.get_top_headlines(q: "crime")
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[ show ]

  # GET /places or /places.json
  def index
    @places = Place.where(['name LIKE ?', "%#{params[:search]}%"])
    @crimes = Location.all
  end

  # GET /places/1 or /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # POST /places or /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: "Place was successfully created." }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:name, :latitude, :longitude)
    end
end

app/controllers/police_controller.rb
class PoliceController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/police_helper.rb
module PoliceHelper
end

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-5 ">
    <%= form.label :address, "What is the address of where the crime took place?",  class: "col-10 col-form-label"  %>
    <%= form.text_area :address, rows: 1 ,class: "form-control", required: true  %>
  </div>

    <div class="form-group col-3">
    <%= form.label :city, "What is the city name?",  class: "col-10 col-form-label"  %>
    <%= form.text_area :city, rows: 1, class: "form-control", required: true  %>
  </div>

  <div class="form-group col-5">
    <%= form.label :DateAndTime, "What is the date and time this occurred?", class: "col-10 col-form-label" %>
    <%= form.text_field :datetime,type: "datetime-local", class: "form-control", required: true  %>
  </div>
  <div class="form-group col-8">
    <%= form.label :type, "What is the type of crime?", class: "col-5 col-form-label"%>
    <%= form.select :typec, options_for_select(["Burglary", "Criminal Damage", "Drugs", "Fraud & Forgery", "Robbery", "Sexual Offences","Theft", "Assault", "Harassment", "Murder", "Assault involving weapon", "GBH", "Hate Crime", "Other"]), {include_blank:true}, class: "form-control" , required: true %>
  </div>


  <div class="form-group col-10">
    <%= form.label :description, "Describe the event, including as many details as you can:",  class: "col-10 col-form-label" %>
    <%= form.text_area :description, rows: 5 ,class: "form-control" , required: true%>
  </div>

  <div class="form-group col-10">
    <%= form.label :evidence, class: "col-5 col-form-label" %>
    <%= form.file_field :image %>
  </div>
  <br></br>



  <div class="actions">
    <%= form.submit "Send Report", class: "btn btn-success" %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<div class="main">


<div class="jumbotron text-center">
  <h1>Editing Location</h1>
</div>


<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<br>
<div class="container">
  <div class="jumbotron text-center">
    <h1>Report Submissions</h1>


<div class="jumbotron text-center">
<%= form_tag(locations_path, method: :get) do %>
    <div class="form-outline input-group">
    <%= text_field_tag(:search, params[:search], placeholder: "Search by city name", class: "form-control") %>
  <%= submit_tag ("Search"), class: "btn btn-outline-success my-2 my-sm-0" %>
  <% end %>
</div></div>
<br>

<% @locations.each do|location| %>
  <div class="card mb-3">
    <% if location.image.attached? %>
      <img class="card-img-top" src="<%= url_for(location.image) %>" alt="Card image cap" style="height:200px;">      <div class="card-body">
        <h5 class="card-title"><%= location.typec %></h5>
        <h6 class="card-text"><%= location.address %></h6><br/>
        <p class="card-text"><%= location.description%></p>
        <p class="card-text"><small class="text-muted"><%= time_ago_in_words(location.datetime) %></small>    <%= location.city %></p>
        <%= link_to 'View', location_path(location), class:"btn btn-outline-info" %>
        <% if current_model && current_model.admin? %>
          <%= link_to 'Edit', edit_location_path(location), class:"btn btn-outline-primary" %>
          <%= link_to 'Delete', location_path(location), class:"btn btn-outline-danger", method: :delete, data:{confirm: "Are you sure?"} %>
        <% end %>
      </div>
    <% else %>
      <div class="card-body">
        <h5 class="card-title"><%= location.typec %></h5>
        <h6 class="card-text"><%= location.address %></h6><br/>
        <p class="card-text"><%= location.description%></p>
        <p class="card-text"><small class="text-muted"><%= time_ago_in_words(location.datetime) %></small>    <%= location.city %></p>
        <%= link_to 'View', location_path(location), class:"btn btn-outline-info" %>
        <% if current_model && current_model.admin? %>
          <%= link_to 'Edit', edit_location_path(location), class:"btn btn-outline-primary" %>
          <%= link_to 'Delete', location_path(location), class:"btn btn-outline-danger", method: :delete, data:{confirm: "Are you sure?"} %>
        <% end %>
    <% end %>
    </div>
  </div>
<% end %>
<%= link_to 'New Form', new_location_path, class:"btn btn-secondary" %>

</div>
</div>

app/views/locations/new.html.erb
<div class="main">


<div class="jumbotron text-center">
    <h1>Report Submission Form</h1>
</div>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>


</div>

app/views/locations/show.html.erb
<div class="main">
<h4> View Report </h4><br/>

  <div class="card mb-3">
    <% if @location.image.attached? %>
    <img class="card-img-top" src="<%= url_for(@location.image) %>" alt="Card image cap" style="height:500px;">
      <div class="card-body">
        <h5 class="card-title"><%= @location.typec %></h5>
        <h6 class="card-text"><%= @location.address %></h6><br/>
        <p class="card-text"><%= @location.description%></p>
        <p class="card-text"><small class="text-muted"><%= time_ago_in_words(@location.datetime) %></small>    <%= @location.city %></p>
        <% if current_model && current_model.admin %>  
          <%= link_to 'Edit', edit_location_path(@location), class:"btn btn-outline-primary" %>
          <%= link_to 'Delete', location_path(@location), class:"btn btn-outline-danger", method: :delete, data:{confirm: "Are you sure?"} %>
        <% end %>
        <%= link_to 'Back to all submissions', locations_path, type: "button", class:"btn btn-outline-secondary" %>
      </div>
    <% else %>
    <div class="card-body">
      <h5 class="card-title"><%= @location.typec %></h5>
      <h6 class="card-text"><%= @location.address %></h6><br/>
      <p class="card-text"><%= @location.description%></p>
      <p class="card-text"><small class="text-muted"><%= time_ago_in_words(@location.datetime) %></small>    <%= @location.city %></p>
      <% if current_model && current_model.admin %>
        <%= link_to 'Edit', edit_location_path(@location), class:"btn btn-outline-primary" %>
        <%= link_to 'Delete', location_path(@location), class:"btn btn-outline-danger", method: :delete, data:{confirm: "Are you sure?"} %>
      <% end %>
      <%= link_to 'Back to all submissions', locations_path, type: "button", class:"btn btn-outline-secondary" %>
    </div>
  </div>
  
    <% end %>
    <h3>Comments </h3>
    <% @location.comments.each do |comment|%>
      <div class="well">
        <p><strong><%= comment.username %></strong>: <%= comment.body %></p>
        <small><%= time_ago_in_words(comment.created_at) %> ago </small>
      </div>
    <% end %>
    <hr>

    <h4>Add Comment</h4>
    <%= form_for([@location, @location.comments.build]) do |f| %>
      <p>
        <%= f.label :username%><br>
        <%= f.text_field(:username, {:class => 'form-control', required: true}) %>
      </p>
      <p>
        <%= f.label :body%>
        <%= f.text_field(:body, {:class => 'form-control', required: true}) %>
      </p>
      <p>
        <%= f.submit({:class => 'btn btn-success'})%>
      </p>
      <% end %>
    </div>